name: No me quiero caer
attire:
  active: null
  user_permissions:
    can_toggle_visibility: true
  visible: false
blocks:
  defaultToolbox: |
      <category name="COMANDOS">
      </category>
        <category name="Comandos primitivos">
          <block type="Poner"></block>
          <block type="Sacar"></block>
          <block type="Mover"></block>
          <block type="IrAlBorde"></block>
          <block type="VaciarTablero"></block>
        </category>
        <category name="Procedimientos primitivos">
        </category>
        <category name="Mis procedimientos" custom="PROCEDURE_CALLS">
        </category>
        <category name="Alternativas">
          <block type="AlternativaSimple"></block>
          <block type="AlternativaCompleta"></block>
        </category>
        <category name="Repeticiones">
          <block type="RepeticionSimple"></block>
          <block type="RepeticionCondicional"></block>
        </category>
        <category name="Asignación">
          <block type="Asignacion"></block>
        </category>
      <category name="EXPRESIONES">
      </category>
        <category name="Valores literales">
          <block type="math_number"></block>
          <block type="ColorSelector"></block>
          <block type="DireccionSelector"></block>
          <block type="BoolSelector"></block>
        </category>
        <category name="Expresiones primitivas">
          <block type="hayBolitas"></block>
          <block type="puedeMover"></block>
          <block type="nroBolitas"></block>
        </category>
        <category name="Funciones primitivas">
        </category>
        <category name="Mis funciones" custom="FUNCTION_CALLS">
        </category>
        <category name="Operadores">
          <block type="OperadorNumerico"></block>
          <block type="OperadorDeComparacion"></block>
          <block type="OperadorLogico"></block>
          <block type="not"></block>
          <block type="siguiente"></block>
          <block type="previo"></block>
          <block type="opuesto"></block>
        </category>
      <category name="DEFINICIONES">
      </category>
        <category name="Procedimientos">
          <block type="procedures_defnoreturnnoparams"></block>
          <block type="procedures_defnoreturn"></block>
        </category>
        <category name="Funciones">
          <block type="procedures_defreturnsimple"></block>
          <block type="procedures_defreturnsimplewithparams"></block>
          <block type="procedures_defreturn"></block>
        </category>
        <category name="Programas">
          <block type="Program"></block>
          <block type="InteractiveProgram"></block>
        </category>
        <category name="Asociaciones">
          <block type="InteractiveLetterBinding"></block>
          <block type="InteractiveNumberBinding"></block>
          <block type="InteractiveKeyBinding"></block>
        </category>
      <category name="Auxiliares Docente">
        <block type="ComandoCompletar"></block>
        <block type="ExpresionCompletar"></block>
        <block type="AsociacionDeTeclaCompletar"></block>
      </category>
  disabled: [ "Sacar", "IrAlBorde"
            , "nroBolitas", "hayBolitas", "OperadorNumerico"
            , "siguiente", "previo", "opuesto"
            ]
  visible:  [ "COMANDOS"    , "Poner", "Mover", "Sacar", "IrAlBorde"
                            , "Procedimientos primitivos"
                            , "Mis procedimientos"
                            , "RepeticionSimple"
                            , "AlternativaCompleta"
            , "EXPRESIONES" , "Color", "Direccion", "Numero"
                            , "nroBolitas", "hayBolitas", "puedeMover"
                            , "FuncionesPrimitivas"
                            , "OperadorNumerico"
                            , "siguiente", "previo", "opuesto"
            , "DEFINICIONES", "procedures_defnoreturn"
            ]
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: true
execution_speed:
  active: instantaneous
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.75
